
font_size 14.5

font_family      Iosevka Term SS08
bold_font        Iosevka Term SS08 Medium
italic_font      Iosevka Term SS08 Oblique
bold_italic_font Iosevka Term SS08 Medium Oblique

modify_font cell_height 115%


selection_foreground #0a0a0a
selection_background #e6e6e6

strip_trailing_spaces smart

cursor #89b4fa	
cursor_text_color #cdd6f4
cursor_shape beam 
cursor_beam_thickness 2.0
cursor_underline_thickness 2.0
cursor_blink_interval -1
cursor_stop_blinking_after 15

select_by_word_characters :-./_~?&=%+#

tab_bar_min_tabs            1
tab_bar_edge                top
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

# tab_bar_style       fade
# tab_fade 0.25 0.5 0.75 1
# tab_powerline_style angled
# tab_separator " ┇"
# tab_bar_margin_height 0.0 0.0
# tab_title_max_length 25
# # tab_title_template  "{index} {title[:10]}"
# tab_title_template "{index} {bell_symbol}{activity_symbol}{title}"
# # tab_title_template "{index} {f'{title[:10]}…' if title.rindex(title[-1]) + 1 > 30 else (title.center(6) if (title.rindex(title[-1]) + 1) % 2 == 0 else title.center(5))}"
# active_tab_font_style bold
# inactive_tab_font_style normal
# tab_bar_edge top
# active_tab_background #89b4fa
# bar_bar_style powerline
