
font_size 13

# font_family      Iosevka Term SS08
# bold_font        Iosevka Term SS08 Medium
# italic_font      Iosevka Term SS08 Oblique
# bold_italic_font Iosevka Term SS08 Medium Oblique
#
font_family      Fira Code Regular
bold_font        Fira Code Bold
italic_font      Fira Code Italic
bold_italic_font Fira Code Bold Italic
modify_font cell_height 110%


selection_foreground #0a0a0a
selection_background #e6e6e6

strip_trailing_spaces smart

cursor #89b4fa	
cursor_text_color #cdd6f4
cursor_shape beam 
cursor_beam_thickness 2.0
cursor_underline_thickness 2.0
cursor_blink_interval -1
cursor_stop_blinking_after 15

select_by_word_characters :-./_~?&=%+#

tab_bar_style       custom
tab_separator       ""
# tab_title_template  "{index} {title[:10]}"
tab_title_template "{f'{title[:10]}…' if title.rindex(title[-1]) + 1 > 30 else (title.center(6) if (title.rindex(title[-1]) + 1) % 2 == 0 else title.center(5))}"
active_tab_font_style bold
inactive_tab_font_style normal
tab_bar_edge top
active_tab_background #89b4fa
bar_bar_style powerline
