kitty
hyprland
sddm
dunst
hyprpaper
hypridle
hyprlock
playerctl
brightnessctl
pamixer
telegram-desktop
discord
xdg-desktop-portal-hyprland
polkit-kde-agent
qt5-wayland
qt6-wayland
waybar
nwg-look
qt6ct
stow
zsh
tmux
zoxide
bat
starship
fzf
go
rustup
ripgrep
fd
glab
github-cli
