include ./config/theme.conf
include ./config/startup.conf
include ./config/font.conf
include ./config/keymaps.conf


font_size 15.5

font_family      Iosevka Term SS08
# font_family      JetBrainsMono Nerd Font
bold_font        Iosevka Term SS08 Medium
italic_font      Iosevka Term SS08 Oblique
bold_italic_font Iosevka Term SS08 Medium Oblique

disable_ligatures never

selection_foreground #0a0a0a
selection_background #e6e6e6

# Strip spaces at end of normal (non-rectangle) selections
strip_trailing_spaces smart

# Characters considered part of words when double-clicking
select_by_word_characters :-./_~?&=%+#

kitty_mod ctrl+shift
