font_family      Iosevka Nerd Font
bold_font        Iosevka Nerd Font Bold
italic_font      Iosevka Nerd Font Oblique
bold_italic_font Iosevka Nerd Font Heavy Oblique

font_size 16

cursor_shape block
cursor_blink_interval 0

underline_hyperlinks always

# BEGIN_KITTY_THEME
# Catppuccin-Macchiato
include current-theme.conf
# END_KITTY_THEME
