include ./config/theme.conf
include ./config/startup.conf
include ./config/font.conf
include ./config/keymaps.conf


font_size 14

# font_family      Iosevka Term SS04
# font_family      JetBrainsMono Nerd Font
# bold_font        Iosevka Term SS04 Medium
# italic_font      Iosevka Term SS04 Oblique
# bold_italic_font Iosevka Term SS04 Medium Oblique

font_family      JetBrains Mono 
bold_font        JetBrains Mono SemiBold
italic_font      JetBrains Mono Italic
bold_italic_font JetBrains Mono SemiBold Italic
disable_ligatures always


cursor_shape block

mouse_hide_wait 4.0

# Selection {{{

selection_foreground #0a0a0a
selection_background #e6e6e6

# Strip spaces at end of normal (non-rectangle) selections
strip_trailing_spaces smart

# Characters considered part of words when double-clicking
select_by_word_characters :-./_~?&=%+#

kitty_mod ctrl+shift
