source=/home/sergio/.config/hypr/hyprland/mocha.conf # Theme
source=/home/sergio/.config/hypr/conf/programs.hyprland.conf
source=/home/sergio/.config/hypr/conf/binds.hyprland.conf
source=/home/sergio/.config/hypr/conf/autostart.hyprland.conf
source=/home/sergio/.config/hypr/conf/monitors.hyprland.conf
source=/home/sergio/.config/hypr/conf/env.hyprland.conf
source=/home/sergio/.config/hypr/conf/appearance.hyprland.conf
source=/home/sergio/.config/hypr/conf/input.hyprland.conf
source=/home/sergio/.config/hypr/conf/rules.hyprland.conf
