source=./config/theme.conf
source=./config/programs.hyprland.conf
source=./config/binds.hyprland.conf
source=./config/autostart.hyprland.conf
source=./config/monitors.hyprland.conf
source=./config/env.hyprland.conf
source=./config/appearance.hyprland.conf
source=./config/input.hyprland.conf
source=./config/rules.hyprland.conf
