windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.
# Float rules
$center-float-large = class:^(center-float-large)$|^(.*Geeqie.*)$|^(.*geeqie.*)$|^(.*celluloid.*)$|^(.*mpv.*)$|^(.*org.qbittorrent.qBittorrent.*)$
windowrulev2 = float, $center-float-large
windowrulev2 = size 75% 75%, $center-float-large
windowrulev2 = center 1, $center-float-large

$center-float = class:^(center-float)$|^(.*file-roller.*)$|^(.*FileRoller.*)$
$center-float-title = title:^(.*Open Folder.*)$|^(.*Open File.*)$|^(.*Save File.*)$|^(.*Save Folder.*)$|^(.*Save Image.*)$|^(.*Save As.*)$|^(.*Open As.*)$|^(.*org.kde.kcalc.*)$|^(.*All Files.*)$
windowrulev2 = float, $center-float
windowrulev2 = float, $center-float-title
windowrulev2 = size 60% 60%, $center-float
windowrulev2 = size 60% 60%, $center-float-title
windowrulev2 = center 1, $center-float
windowrulev2 = center 1, $center-float-title


$center-float-mini = class:^(center-float-mini)$|^(.*galculator.*)$|^(.*ytdlp-gui.*)$
windowrulev2 = float, $center-float-mini
windowrulev2 = size 40% 40%, $center-float-mini
windowrulev2 = center 1, $center-float-mini

windowrulev2 = float, class:org.pulseaudio.pavucontrol
windowrulev2=float,class:blueman-manager
windowrulev2=float, title:^(Bitwarden)(.*)$
windowrulev2=float, title:^(Location)(.*)$
windowrulev2=float,title:^(Mullvad VPN)(.*)$
windowrulev2=float,title:^(Open File)(.*)$
windowrulev2=float,title:^(rofi)(.*)$
windowrulev2=float,title:^(Select a File)(.*)$
windowrulev2=float,title:^(Choose wallpaper)(.*)$
windowrulev2=float,title:^(Open Folder)(.*)$
windowrulev2=float,title:^(Save As)(.*)$
windowrulev2=float,title:^(Library)(.*)$
windowrulev2=float,title:^(File Upload)(.*)$
windowrulev2=float,title:^(KCalc)(.*)$

# Center rules
windowrulev2=center, class:blueman-manager
windowrulev2 = center, class:org.pulseaudio.pavucontrol
windowrulev2=center, title:^(Open File)(.*)$
windowrulev2=center, title:^(Select a File)(.*)$
windowrulev2=center, title:^(Choose wallpaper)(.*)$
windowrulev2=center, title:^(Open Folder)(.*)$
windowrulev2=center, title:^(Save As)(.*)$
windowrulev2=center, title:^(Library)(.*)$
windowrulev2=center, title:^(File Upload)(.*)$
windowrulev2=center, title:^(rofi)(.*)$
windowrulev2=center, title:^(Mullvad VPN)(.*)$
windowrulev2=center, title:^(Location)(.*)$
windowrulev2=center, title:^(Volume Control)(.*)$
windowrulev2=center,title:^(KCalc)(.*)$


workspace=1,gapsin:0,gapsout:0,bordersize:0,persistent,monitor:eDP-1,default:true

windowrulev2 = tile,class:^(firefox)$
windowrulev2 = workspace 1,class:^(vivaldi-stable)$
windowrulev2 = workspace 2,class:^(kitty)$

# pavucontrol
windowrulev2 = size 800x600, class:org.pulseaudio.pavucontrol

# blueman applet
windowrulev2 = size 800x600, class:blueman-manager

# Layer Rules
layerrule = animation popin, rofi
layerrule = blur, rofi
layerrule = ignorezero, rofi

layerrule = blur, waybar
layerrule = ignorezero, waybar

layerrule = ignorezero, swaync-notification-window
layerrule = animation slide, swaync-notification-window
layerrule = animation slide, swaync-control-center

layerrule = animation fade, swayosd

layerrule = animation fade, selection
layerrule = animation fade, hyprlock

layerrule = noanim, hyprpicker
