
#####################
### LOOK AND FEEL ###
#####################

general { 
    gaps_in = 0
    gaps_out = 0

    border_size = 0

    col.active_border = rgba($blueAlphadd) rgba($skyAlphadd) 90deg
    col.inactive_border = rgba(595959aa)

    resize_on_border = false 

    allow_tearing = false

    layout = dwindle
}

xwayland {
  force_zero_scaling = true
}

decoration {
    rounding = 2


    blur {
      enabled = false
      size = 5
      passes = 3
      new_optimizations = true
      vibrancy = 0.2
    }
    # Change transparency of focused and unfocused windows
    active_opacity = 1
    inactive_opacity = 1.0

    drop_shadow = false
    # shadow_range = 4
    # shadow_render_power = 3
    # col.shadow = rgba(1a1a1aee)
    # layerrule = blur,waybar
    # layerrule = blur,rofi
    # layerrule = blur,kitty
}

animations {

    enabled = true
    bezier = default, 0.05, 0.9, 0.1, 1.05
    bezier = wind, 0.05, 0.9, 0.1, 1.05
    bezier = overshot, 0.13, 0.99, 0.29, 1.08
    bezier = liner, 1, 1, 1, 1

    animation = windows, 1, 7, wind, popin
    animation = windowsIn, 1, 7, overshot, popin
    animation = windowsOut, 1, 5, overshot, popin
    animation = windowsMove, 1, 6, overshot, slide
    animation = layers, 1, 5, default, popin
    animation = fadeIn, 1, 10, default
    animation = fadeOut, 1, 10, default
    animation = fadeSwitch, 1, 10, default
    animation = fadeShadow, 1, 10, default
    animation = fadeDim, 1, 10, default
    animation = fadeLayers, 1, 10, default
    animation = workspaces, 1, 3, overshot, slide
    animation = border, 1, 1, liner
    animation = borderangle, 1, 30, liner, loop

    # bezier = myBezier, 0.35, 0.4, 0.67, 0.99
    # # cubic-bezier(.35,.4,.67,.58)
    # bezier = secondBezier, 0, 0.85, 0.15, 0.99
    # bezier = easeInBezier, 0.42, 0.0, 1, 1
    # # {"ease":".25,.1,.25,1","linear":"0,0,1,1","ease-in":".42,0,1,1","ease-out":"0,0,.58,1","ease-in-out":".42,0,.58,1"}
    #
    # animation = windows, 1, 3, default
    # animation = windowsOut, 1, 7, default, popin 80%
    # animation = border, 1, 10, default
    # animation = borderangle, 1, 8, default
    # animation = fade, 1, 5, secondBezier
    # animation = workspaces, 1, 1, easeInBezier
}

dwindle {
  pseudotile = true
  preserve_split = true
}

master {
    # new_is_master = true
}

misc { 
    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
    animate_manual_resizes = true
    animate_mouse_windowdragging = true
    enable_swallow = true
    render_ahead_of_time = false
    disable_hyprland_logo = true

    font_family = "Noto Sans Regular 10"

}



