###################
### MY PROGRAMS ###
###################

$terminal = kitty
$browser = firefox
$editor = nvim
$notes = obsidian
$music = spotify
$word = librewriter
$fileManager = nautilus
$screenshot = hyprshot


